import streamlit as st
import pandas as pd
import yfinance as yf
import time

st.set_page_config(page_title="Live Frontier Scanner", layout="wide")

st.title("🛡️ Live Frontier Discovery Engine")
st.info("Unbiased Protocol: This app queries live industry indices. No tickers are hand-picked.")

# --- THE DYNAMIC INDUSTRY MAP ---
# Instead of tickers, we define the 'Industry Keys' used by the market
industries = {
    "🌀 Quantum & Specialized Tech": "computer-hardware",
    "🔌 AI Infrastructure & Chips": "semiconductors",
    "🤖 Software & AI Platforms": "software-infrastructure",
    "🔥 Energy & Uranium (AI Fuel)": "other-precious-metals",
    "🏗️ Infrastructure & Rail": "railroads"
}

for label, ind_key in industries.items():
    st.header(label)
    try:
        # Step 1: Query the actual industry for its top players
        ind_data = yf.Industry(ind_key)
        # Pull the top companies by market weight/relevance
        top_players = ind_data.top_companies.index.tolist()[:4] 
        
        cols = st.columns(4)
        for i, ticker in enumerate(top_players):
            # Step 2: Get 5-year data for these market-selected winners
            t_obj = yf.Ticker(ticker)
            hist = t_obj.history(period="5y")
            
            if not hist.empty:
                with cols[i]:
                    curr_p = hist['Close'].iloc[-1]
                    growth = ((curr_p - hist['Close'].iloc[0]) / hist['Close'].iloc[0]) * 100
                    st.metric(label=ticker, value=f"${curr_p:.2f}", delta=f"{growth:.1f}%")
                    st.line_chart(hist['Close'], height=150)
            
            time.sleep(0.5) # Protect your connection limit
    except Exception as e:
        st.write(f"Scanning the {label} sector for today's leaders...")
    st.divider()

st.subheader("🧠 Peer-to-Peer Decision Tool")
st.write("Because this list is generated by the market, you might see companies you've never heard of. That is where '100x' potential often hides.")
